# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('selected', models.BooleanField(default=True, verbose_name='是否选择')),
            ],
        ),
    ]
