# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未付款'), (1, '配送中'), (2, '已完成'), (3, '待评价'), (4, '售后中'), (5, '已删除')], default=0, verbose_name='订单状态')),
                ('user_id', models.IntegerField(verbose_name='用户编号')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_no', models.CharField(max_length=256, verbose_name='订单号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='实际支付')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('coupon_price', models.IntegerField(verbose_name='优惠价格')),
                ('credit_price', models.IntegerField(verbose_name='积分抵扣价格')),
                ('discount', models.IntegerField(verbose_name='折扣价格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单总价')),
            ],
        ),
        migrations.CreateModel(
            name='Order_to_Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('good_id', models.IntegerField(verbose_name='商品ID')),
                ('good_num', models.IntegerField(verbose_name='商品数量')),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品单价')),
            ],
        ),
    ]
