# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-22 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_remove_goods_productid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='goodtypes',
            table='goodtypes',
        ),
    ]
